tax-permissions:
  sellall-tax-0: 0
  sellall-tax-10: 10
  sellall-tax-20: 20
  sellall-tax-30: 30
  sellall-tax-40: 40
  sellall-tax-50: 50
  sellall-tax-60: 60
  sellall-tax-70: 70
  sellall-tax-80: 80
  sellall-tax-90: 90

worth-tiers:
  1: 100
  64: 75
  96: 50
  150: 25
  250: 10

mysql:
  host: localhost
  port: 3306
  table_prefix: ''
  database: minecraft
  username: root
  password: password

no_permission_message: '&cYou are not allowed to do this!'
reload_message: '&aReloaded the plugin!'
invalid_player_message: '&cThere is no player with that name!'
menu_opened_other_message: '&aOpened the menu for %player%'
no_menu_specified: '&cPlease specify which menu you want to open: &7/sellall <menu>'
invalid_menu: '&cNo menu could be found with that name!'