name: SellAll
version: ${project.version}
description: Custom Sell All plugin
author: GaagjesCraft Network Team
main: net.gcnt.sellall.SellAll
api-version: 1.13
depend:
  - Vault

commands:
  sellall:
    description: SellAll command