name: SellAll
version: ${project.version}
description: Custom Sell All plugin
author: Devmart (GCNT)
main: net.gcnt.sellall.SellAll
api-version: 1.19
depend:
  - Vault
  - MMOItems
  - Oraxen

commands:
  sellall:
    description: SellAll command